
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_php
    working_dir: /var/www/html
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db
    networks:
      - symfony

  nginx:
    image: nginx:1.27-alpine
    container_name: symfony_nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - symfony

  db:
    image: mysql:8.0
    container_name: symfony_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: currency_db
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - symfony

  react_frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react_frontend
    working_dir: /app
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_BASE_URL=http://symfony_nginx/api
    networks:
      - symfony
    command: ["npm", "run", "dev", "--", "--host"]    

networks:
  symfony:

volumes:
  db_data:
